[package]
name = "{{project-name}}" # TODO 修改
version = "0.1.0"
authors=["{{authors}}"] # TODO 修改

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]