# deny.toml (for cargo-deny >= 0.13)

[advisories]
unmaintained = "all"
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = ["MIT", "Apache-2.0"]
private = { ignore = true }
confidence-threshold = 0.8

[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "wasm32-unknown-unknown"
]
