# deny.toml (for cargo-deny >= 0.13)

[advisories]
enabled = true
severity-threshold = "medium"  # 可选：low, medium, high, critical
vulnerability = { severity = "deny" }
unmaintained = { severity = "warn", scope = "all" }
yanked = { severity = "warn" }
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0"]
copyleft = { severity = "warn" }
private = { ignore = true }
confidence-threshold = 0.8

[graph]
targets = [
  { name = "x86_64-unknown-linux-gnu" },
  { name = "x86_64-pc-windows-msvc" },
  { name = "wasm32-unknown-unknown" },
]
